networks:
  kafka-net:
    driver: bridge

services:
  minio:
      image: quay.io/minio/minio
      container_name: minio
      ports:
        - "9000:9000"
        - "9001:9001"
      environment:
        MINIO_ROOT_USER: ${MINIO_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      volumes:
        - ./minio/data:/data
      command: server /data --console-address ":9001"

  kafka_1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka_1
    container_name: kafka_1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka_1:9093,2@kafka_2:9093,3@kafka_3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka_1:9092,CONTROLLER://kafka_1:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka_1:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'AEwq7cqhRkKqoOCkVDoRfg'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./.kafka-storage/kafka-1/data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka_2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka_2
    container_name: kafka_2
    ports:
      - "9094:9092"
      - "9095:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka_1:9093,2@kafka_2:9093,3@kafka_3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka_2:9092,CONTROLLER://kafka_2:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka_2:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'AEwq7cqhRkKqoOCkVDoRfg'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./.kafka-storage/kafka-2/data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka_3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka_3
    container_name: kafka_3
    ports:
      - "9096:9092"
      - "9097:9093"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka_1:9093,2@kafka_2:9093,3@kafka_3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka_3:9092,CONTROLLER://kafka_3:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka_3:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'AEwq7cqhRkKqoOCkVDoRfg'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./.kafka-storage/kafka-3/data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_1:9092,kafka_2:9092,kafka_3:9092
    depends_on:
      - kafka_1
      - kafka_2
      - kafka_3
    networks:
      - kafka-net