global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Airflow DAGs and Spark Jobs
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['siem-pushgateway:9091']

  # Throughput and Consumer Lag
  - job_name: 'kafka-cluster'
    static_configs:
      - targets: ['siem-kafka-exporter:9308']